

# Auto-generated by Interface Designer
#
# WARNING: Any manual changes made to this file will be lost when generating constraints.

# Efinity Interface Designer SDC
# Version: 2024.1.163.2.15
# Date: 2024-08-12 15:51

# Copyright (C) 2013 - 2024 Efinix Inc. All rights reserved.

# Device: T120F324
# Project: efinity_spi_comm
# Timing Model: C4 (final)

# PLL Constraints
#################
create_clock -period 8.3333 main_clock

# GPIO Constraints
####################
# set_input_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -max <MAX CALCULATION> [get_ports {spi_clock}]
# set_input_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -min <MIN CALCULATION> [get_ports {spi_clock}]
# set_input_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -max <MAX CALCULATION> [get_ports {spi_cs_in}]
# set_input_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -min <MIN CALCULATION> [get_ports {spi_cs_in}]
# set_input_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -max <MAX CALCULATION> [get_ports {spi_data_in}]
# set_input_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -min <MIN CALCULATION> [get_ports {spi_data_in}]
# set_input_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -max <MAX CALCULATION> [get_ports {spi_data_out}]
# set_input_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -min <MIN CALCULATION> [get_ports {spi_data_out}]

# spi_clock from the FTDI clocks the spi shift registers directly, 30 MHz max
create_clock -period 33.333 -name spi_clock [get_ports {spi_clock}]
set_clock_groups -asynchronous -group {main_clock} -group {spi_clock}
